name: Run tests

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download required solidity compilers
        run: |
          mkdir -p ~/.solcx/ 
          wget -O ~/.solcx/solc-v0.7.2 https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.7.2+commit.51b20bc0 
          wget -O ~/.solcx/solc-v0.8.2 https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.2+commit.661d1103 
          wget -O ~/.solcx/solc-v0.8.15 https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.15+commit.e14f2714 
          chmod 755 ~/.solcx/solc* 
      
      - name: Download brownie dependencies
        run: |
          export VERSION_OPEN_ZEPPELIN=4.7.0
          export VERSION_CHAINLINK=1.6.0
          wget -O /tmp/v${VERSION_OPEN_ZEPPELIN}.tar.gz https://github.com/OpenZeppelin/openzeppelin-contracts/archive/refs/tags/v${VERSION_OPEN_ZEPPELIN}.tar.gz 
          wget -O /tmp/v${VERSION_CHAINLINK}.tar.gz https://github.com/smartcontractkit/chainlink/archive/refs/tags/v${VERSION_CHAINLINK}.tar.gz
          mkdir -p ~/.brownie/packages/OpenZeppelin 
          cd ~/.brownie/packages/OpenZeppelin 
          tar xvfz /tmp/v${VERSION_OPEN_ZEPPELIN}.tar.gz 
          mv openzeppelin-contracts-${VERSION_OPEN_ZEPPELIN} openzeppelin-contracts@${VERSION_OPEN_ZEPPELIN} 
          mkdir -p ~/.brownie/packages/smartcontractkit 
          cd ~/.brownie/packages/smartcontractkit 
          tar xvfz /tmp/v${VERSION_CHAINLINK}.tar.gz 
          mv chainlink-${VERSION_CHAINLINK} chainlink@${VERSION_CHAINLINK}

      - name: Install ganache
        run: npm install --global ganache-cli

      - name: Setup brownie
        run: wget https://raw.githubusercontent.com/eth-brownie/brownie/master/requirements.txt
      - run: pip install -r requirements.txt 
      - run: pip install eth-brownie 

      - name: Compile contracts
        run: brownie compile --all
      
      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          ignore-compile: true
          solc-version: 0.8.2

        