name: Solidity static code analysis

on: 
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 📊 Crunch Numbers
        uses: tintinweb/solidity-metrics-action@v1
        id: metrics
        with:
            target: 'contracts/{,**/}*.sol'
      - uses: actions/upload-artifact@v3
        with:
          name: metrics.html
          path: ${{ steps.metrics.outputs.report }}
      - uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        # with:
        #   sarif: results.sarif